chains:
  - name: okp4-1
    type: custom
    numValidators: 1
    image: anmol1696/okp4d:latest
    home: /root/.okp4d
    binary: okp4d
    prefix: okp4
    denom: uknow
    coins: 100000000000000uknow
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/okp4/okp4d
    ports:
      rest: 1317
      rpc: 26657
      faucet: 8007
    resources:
      cpu: "0.2"
      memory: "200M"
  - name: gaia-1
    type: cosmos
    numValidators: 1
    ports:
      rest: 1313
      rpc: 26653
      faucet: 8003
    resources:
      cpu: "0.2"
      memory: "200M"

relayers:
  - name: okp4-gaia
    type: hermes
    replicas: 1
    chains:
      - okp4-1
      - gaia-1
    resources:
      cpu: "0.1"
      memory: "100M"

registry:
  enabled: true
  ports:
    rest: 8081
  resources:
    cpu: "0.1"
    memory: "100M"

exposer:
  resources:
    cpu: "0.1"
    memory: "100M"

faucet:
  resources:
    cpu: "0.1"
    memory: "100M"
